/******************************************************************************/
/*                         DNS Manutenções - 2018                             */
/******************************************************************************/

package dns.manutenções.view;

import dns.manutenções.control.Controlador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author danie_000
 */
public class ServicosPanel extends javax.swing.JPanel
{
    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control;
    
    DefaultListModel funcionariosListModel = new DefaultListModel();
    DefaultListModel clientesListModel = new DefaultListModel();
    DefaultListModel pecasListModel = new DefaultListModel();
    DefaultListModel servicosListModel = new DefaultListModel();

    DefaultComboBoxModel clientesBox = new DefaultComboBoxModel();
    DefaultComboBoxModel funcionariosBox = new DefaultComboBoxModel();
    
    public void atualizarListaFuncionarios()
    {
        funcionariosListModel.clear();
        
        for(int i = 0; i < control.ctrlFuncionarios().getListaFuncionarios().size(); i++) 
        {
            funcionariosListModel.addElement(control.ctrlFuncionarios().getListaFuncionarios().get(i).getMatricula() + " " + control.ctrlFuncionarios().getListaFuncionarios().get(i).getNome());
        }
    }
    
    public void atualizarListaClientes()
    {
        clientesListModel.clear();
        
        for(int i = 0; i < control.ctrlClientes().getPessoasClientes().size(); i++) 
        {
            clientesListModel.addElement(control.ctrlClientes().getPessoasClientes().get(i).getNome());
        }
        
        for(int i = 0; i < control.ctrlClientes().getEmpresasClientes().size(); i++) 
        {
            clientesListModel.addElement(control.ctrlClientes().getEmpresasClientes().get(i).getNome());
        }
    }
    
    public void atualizarListaPecas()
    {
        pecasListModel.clear();
        
        for(int i = 0; i < control.ctrlPecas().getListaPecas().size(); i++) 
        {
            pecasListModel.addElement(control.ctrlPecas().getListaPecas().get(i).getCodigo() + "       " + control.ctrlPecas().getListaPecas().get(i).getNome() + "       R$" + control.ctrlPecas().getListaPecas().get(i).getPreco());
        }
        
    }
    
    public void atualizarListaServicos()
    {
        servicosListModel.clear();
        
        for(int i = 0; i < control.getServicos().size(); i++) 
        {
            servicosListModel.addElement(control.getServicos().get(i).getCliente());
        }
    }
    
    public void atualizarBoxFuncionarios()
    {
        funcionariosBox.removeAllElements();//Listener Pattern
        
        for(int i = 0; i < control.ctrlClientes().getClientes().size(); i++)
        {
            funcionariosBox.addElement(control.ctrlFuncionarios().getListaFuncionarios().get(i).getNome());
        }
    }
   
    public void atualizarBoxClientes()
    {   
        control.ctrlClientes().atualizarListaClientes();//Observer Pattern
        
        clientesBox.removeAllElements();
        
        for(int i = 0; i < control.ctrlClientes().getClientes().size(); i++)
        {
            clientesBox.addElement(control.ctrlClientes().getClientes().get(i));
        }
        
        /* Atualiza o ComboBox com strings 
        for(int i = 0; i < control.ctrlClientes().getPessoasClientes().size(); i++)
        {
            clientesBox.addElement(control.ctrlClientes().getPessoasClientes().get(i).getNome());
        }
        
        for(int i = 0; i < control.ctrlClientes().getEmpresasClientes().size(); i++)
        {
            clientesBox.addElement(control.ctrlClientes().getEmpresasClientes().get(i).getNome());
        }*/
    }
        
    
    /**
     * Creates new form ClientesPanel
     * @param c
     */
    public ServicosPanel(Controlador c)
    {   
        this.control = c;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        NovoServicoPanel = new javax.swing.JDialog();
        ClientesComboBox = new javax.swing.JComboBox<>();
        FuncionariosComboBox = new javax.swing.JComboBox<>();
        TextoData = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ScrollPanelClientesp4 = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JList();
        ScrollPanelClientesp1 = new javax.swing.JScrollPane();
        ListaPessoas = new javax.swing.JList();
        ScrollPanelClientesp2 = new javax.swing.JScrollPane();
        ListaPeças = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        serviçosLabel = new javax.swing.JButton();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaServiços = new javax.swing.JList();
        AgendarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        NovoServicoPanel.setTitle("Agendar Serviço - DNS Manutenções");
        NovoServicoPanel.setLocation(new java.awt.Point(500, 400));
        NovoServicoPanel.setLocationByPlatform(true);
        NovoServicoPanel.setMaximumSize(new java.awt.Dimension(625, 315));
        NovoServicoPanel.setMinimumSize(new java.awt.Dimension(625, 315));
        NovoServicoPanel.setPreferredSize(new java.awt.Dimension(625, 315));
        NovoServicoPanel.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientesComboBox.setModel(clientesBox);
        NovoServicoPanel.getContentPane().add(ClientesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 30));

        FuncionariosComboBox.setModel(funcionariosBox);
        NovoServicoPanel.getContentPane().add(FuncionariosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 100, 30));

        TextoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextoData.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TextoDataActionPerformed(evt);
            }
        });
        NovoServicoPanel.getContentPane().add(TextoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, -1));
        NovoServicoPanel.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, -1));

        jButton6.setText("Agendar");
        NovoServicoPanel.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 110, 50));

        jButton7.setText("Cancelar");
        NovoServicoPanel.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 110, 50));

        ListaFuncionarios.setModel(funcionariosListModel);
        ListaFuncionarios.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                ListaFuncionariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                ListaFuncionariosFocusLost(evt);
            }
        });
        ListaFuncionarios.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                ListaFuncionariosComponentShown(evt);
            }
        });
        ScrollPanelClientesp4.setViewportView(ListaFuncionarios);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 220));

        ListaPessoas.setModel(clientesListModel);
        ListaPessoas.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                ListaPessoasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                ListaPessoasFocusLost(evt);
            }
        });
        ListaPessoas.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                ListaPessoasComponentShown(evt);
            }
        });
        ScrollPanelClientesp1.setViewportView(ListaPessoas);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, 220));

        ListaPeças.setModel(pecasListModel);
        ListaPeças.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                ListaPeçasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                ListaPeçasFocusLost(evt);
            }
        });
        ListaPeças.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                ListaPeçasComponentShown(evt);
            }
        });
        ScrollPanelClientesp2.setViewportView(ListaPeças);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 130, 220));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Funcionários");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clientes");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Peças");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 110, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valor");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 110, 20));

        setMaximumSize(new java.awt.Dimension(595, 322));
        setMinimumSize(new java.awt.Dimension(595, 322));
        setPreferredSize(new java.awt.Dimension(595, 322));
        setLayout(null);

        serviçosLabel.setText("Serviços");
        serviçosLabel.setDefaultCapable(false);
        add(serviçosLabel);
        serviçosLabel.setBounds(10, 10, 140, 23);

        ListaServiços.setModel(servicosListModel);
        ListaServiços.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                ListaServiçosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                ListaServiçosFocusLost(evt);
            }
        });
        ListaServiços.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                ListaServiçosComponentShown(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaServiços);

        add(ScrollPanelClientesp);
        ScrollPanelClientesp.setBounds(10, 40, 140, 290);

        AgendarButton.setText("Agendar");
        AgendarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AgendarButtonActionPerformed(evt);
            }
        });
        add(AgendarButton);
        AgendarButton.setBounds(160, 10, 120, 50);

        jButton2.setText("Concluir");
        add(jButton2);
        jButton2.setBounds(160, 70, 120, 50);

        jButton8.setText("Gerar relatório");
        add(jButton8);
        jButton8.setBounds(160, 130, 120, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("R$ " + this.control.getWe().getSaldo());
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));
        add(jLabel1);
        jLabel1.setBounds(160, 280, 120, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Saldo atual:");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pendentes"));
        add(jLabel2);
        jLabel2.setBounds(160, 220, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void ListaServiçosFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaServiçosFocusGained
    {//GEN-HEADEREND:event_ListaServiçosFocusGained
        ListaServiços.getSelectedValue();
    }//GEN-LAST:event_ListaServiçosFocusGained

    private void ListaServiçosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaServiçosFocusLost
    {//GEN-HEADEREND:event_ListaServiçosFocusLost
        
    }//GEN-LAST:event_ListaServiçosFocusLost

    private void ListaServiçosComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaServiçosComponentShown
    {//GEN-HEADEREND:event_ListaServiçosComponentShown

    }//GEN-LAST:event_ListaServiçosComponentShown

    private void AgendarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AgendarButtonActionPerformed
    {//GEN-HEADEREND:event_AgendarButtonActionPerformed
        this.atualizarListaClientes();
        this.atualizarListaFuncionarios();
        this.atualizarListaPecas();
        NovoServicoPanel.setVisible(true);
    }//GEN-LAST:event_AgendarButtonActionPerformed

    private void TextoDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextoDataActionPerformed
    {//GEN-HEADEREND:event_TextoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDataActionPerformed

    private void ListaFuncionariosFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusGained
    {//GEN-HEADEREND:event_ListaFuncionariosFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaFuncionariosFocusGained

    private void ListaFuncionariosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusLost
    {//GEN-HEADEREND:event_ListaFuncionariosFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaFuncionariosFocusLost

    private void ListaFuncionariosComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaFuncionariosComponentShown
    {//GEN-HEADEREND:event_ListaFuncionariosComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaFuncionariosComponentShown

    private void ListaPessoasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPessoasFocusGained
    {//GEN-HEADEREND:event_ListaPessoasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPessoasFocusGained

    private void ListaPessoasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPessoasFocusLost
    {//GEN-HEADEREND:event_ListaPessoasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPessoasFocusLost

    private void ListaPessoasComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaPessoasComponentShown
    {//GEN-HEADEREND:event_ListaPessoasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPessoasComponentShown

    private void ListaPeçasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPeçasFocusGained
    {//GEN-HEADEREND:event_ListaPeçasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPeçasFocusGained

    private void ListaPeçasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPeçasFocusLost
    {//GEN-HEADEREND:event_ListaPeçasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPeçasFocusLost

    private void ListaPeçasComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaPeçasComponentShown
    {//GEN-HEADEREND:event_ListaPeçasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPeçasComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarButton;
    private javax.swing.JComboBox<String> ClientesComboBox;
    private javax.swing.JComboBox<String> FuncionariosComboBox;
    private javax.swing.JList ListaFuncionarios;
    private javax.swing.JList ListaPessoas;
    private javax.swing.JList ListaPeças;
    private javax.swing.JList ListaServiços;
    private javax.swing.JDialog NovoServicoPanel;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JScrollPane ScrollPanelClientesp1;
    private javax.swing.JScrollPane ScrollPanelClientesp2;
    private javax.swing.JScrollPane ScrollPanelClientesp4;
    private javax.swing.JFormattedTextField TextoData;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton serviçosLabel;
    // End of variables declaration//GEN-END:variables
}
